<a href="https://colab.research.google.com/github/dancorrea86/Pytorch/blob/main/Tensor_Opera%C3%A7%C3%B5es_Matem%C3%A1ticas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSOR OPERAÇÕES MATEMÁTICAS
- Adição, Subtração, Multiplicação, Divisão, Resto da Divisão, Exponenciação
- Shorthand and uh, Longhand
- Reassignment

In [ ]:
import torch
import numpy as np

In [ ]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [ ]:
# Adição
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
# Adição Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [19]:
# Subtração
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [ ]:
# Subtração Função
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [15]:
# Multiplicação
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [16]:
# Multiplicação long
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [17]:
# Divisão
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [18]:
# Divisão longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [20]:
# Restante da divisão
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [21]:
# Restante da divisão longhang
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [22]:
# Exponenciação
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [23]:
# Exponenciação Longhand
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [24]:
# Reassignmente
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [26]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])